#!/bin/bash

cd android
WORK_DIR=/data/plthook-test
PATH=$ANDROID_HOME/ndk-bundle:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

set -e

echodo() {
  banner "$@"
  "$@"
  echo
}

banner() {
  echo ==========================================
  echo == $@
  echo ==========================================
}

banner sdkmanager tools
# Discard stdout to suppress log size. Test stops when log size > 4M on traivis-ci.
echo yes | sdkmanager tools > /dev/null
echo

banner sdkmanager ndk-bundle
# Discard stdout to suppress log size. Test stops when log size > 4M on traivis-ci.
echo yes | sdkmanager ndk-bundle > /dev/null
echo

echodo sdkmanager --list
echodo ndk-build -B

ARCHS="arm64-v8a armeabi-v7a x86 x86_64"
ARCHS="x86"

for ARCH in $ARCHS; do
  echo no | echodo avdmanager create avd -n test -k "system-images;android-25;google_apis;$ARCH" -f

  banner emulator -avd test -no-window -no-audio
  emulator -avd test -no-window -no-audio &
  EMULATOR_PID=$!
  echo

  echodo android-wait-for-emulator
  echodo adb shell "su root mkdir -p $WORK_DIR"
  echodo adb shell "su root chmod 777 $WORK_DIR"
  echodo adb push libs/$ARCH/libtest.so /sdcard
  echodo adb push libs/$ARCH/testprog /sdcard
  echodo adb shell "su root mv /sdcard/libtest.so /sdcard/testprog $WORK_DIR"
  echodo adb shell "su root chmod 755 $WORK_DIR/libtest.so $WORK_DIR/testprog"
  echodo adb shell "su root env LD_LIBRARY_PATH=$WORK_DIR $WORK_DIR/testprog open"
  kill $EMULATOR_PID
  wait $EMULATOR_PID
done
